groupdocs-total/GroupDocs.Total-Angular

apps/editor/src/styles.less
**Problem:**
There is default serif font in use in Editor for now.
**Solution:**
In the styles.less file was added font-family css-property which was taken from https://github.com/groupdocs-total/GroupDocs.Total-Angular/blob/master/apps/viewer/src/styles.less#L9, i didn't add other lines, because i'm not sure that this should be done (should be done in this commit).
**Tests:**
=> Font-family was added.

apps/editor/src/app/editor-app.component.html
**Problem:**
Editor app component has hard-coded incorrect icon inherited from the Viewer app component.
**Solution:**
Icon code was changed to the correct one.
**Tests:**
=> The main Editor logo was replaced to the correct one.

apps/editor/src/app/editor-app.component.ts
**Problem:**
Page height of new document after saving must be the same as before.
Now document height is collapsed.
**Solution:**
Assigning the default width and height was added.
=> Fix min page height.

libs/comparison/src/lib/comparison-app.component.ts
**How it looks with WA:**
**For:** groupdocs-comparison/GroupDocs.Comparison-for-.NET-WebForms#25
=> Added work-around for correct handling not zero-based pages id.

libs/comparison/src/lib/comparison-app.component.html, libs/comparison/src/lib/result-document/result-document.component.html, libs/comparison/src/lib/result-document/result-document.component.less, libs/editor/src/lib/editor-app.component.html
**Tests:**
One manual test was performed - moving between the highlighted changes in the comparison app.
Any cases of using scrollable directive in the editor app were not found yet.
=> Moving scrollable directive on a new place for editor/comparison.

libs/viewer/src/lib/excel-page.service.ts
**Problem:**
**Solution:**
FF adds `a0` namespace somewhere in the engine, and it looks like https://hg.mozilla.org/mozilla-central/rev/3ecc407c0cc8705ba7b60fbbe8964e794c0a5651#l54.241.
As a work-around was added the line with removal of this namespace.
=> Removing name-spaces added by FF.

libs/editor/src/lib/editor-app.component.less, libs/editor/src/lib/editor-app.component.ts
**Problem:**
1. We have problem with Footer/Header presentation before and after saving changes.
2. We have redundant paddings/margins during using newest Editor API.
**Solution:**
Were made changes that are needed for correct presentation (removed padding/margin) and saving (adding root tags on client-side) edited documents in the Editor app on latest API version. Related PR for back-end: https://github.com/groupdocs-total/GroupDocs.Total-for-NET-MVC/pull/81.
<details>
</details>
=> Required changes for correct save on updated Editor API.

apps/total-angular-e2e/src/integration/conversion.spec.ts, libs/conversion/src/lib/conversion-app.component.ts, libs/conversion/src/lib/conversion-browse-files-modal/conversion-browse-files-modal.component.html, libs/conversion/src/lib/conversion-browse-files-modal/conversion-browse-files-modal.component.ts, libs/conversion/src/lib/conversion-queue/conversion-queue.component.html, libs/conversion/src/lib/conversion-queue/conversion-queue.component.less, libs/conversion/src/lib/conversion.service.ts, libs/conversion/src/lib/models.ts
- Improved filter for the conversion work-items, now it uses both source and destination formats;
- Checkbox `Select all` now disabled before uploading at least one file;
- `Add selected` button now has text label before uploading at least one file;
- Container with conversion work-items now has vertical scroll-bar;
- Conversion main component now sends destination document type (like `Microsoft Word`) to the server-side `Convert` method;
- E2E-tests were updated;
=> Changes/improvements for the new Conversion API.

libs/viewer/src/lib/excel-document/excel-document.component.less, libs/viewer/src/lib/viewer-app.component.html
**Problem:**
In the image mode we can't calculate and render the column with line numbers and the row with column names basing on the html with Excel file content thus the UI code is falling.
**Solution:**
Were added conditions in the main Viewer app component for using the excel-document component only in the case of opening Excel files in the  html mode.
=> Excluded usage excel-document component in Image mode.

libs/annotation/src/lib/annotation-app.component.ts
**Problem:**
Loading the specified by _Absolute path_ default doc was missed in the Annotation app UI.
**Solution:**
Common code for such functionality was replicated from the Viewer app.
<details>
</details>
=> Added code for loading default doc if specified in Annotation config.

libs/viewer/src/lib/excel-document/excel-document.component.ts
**Problem:**
We've got error `Expression has changed after it was checked` on opening Excel file after latest changes.
**Solution:**
We don't switch to sheet if it's number is undefined.
=> Fix for error on Excel opening.

libs/viewer/src/lib/run-presentation/run-presentation.component.ts, libs/viewer/src/lib/viewer-app.component.html, libs/viewer/src/lib/viewer-app.component.less, libs/viewer/src/lib/viewer-app.component.ts
**What were done:**
1. Fixed the non-valid zoom calculating in FF (tested locally).
2. Added text and border for start/stop presentation buttons (tested locally in FF/Chrome).
<details>
_Start/stop buttons border and sliding in FF:_
</details>
=> Slides UI fixes and improvements related to cross-browser compatibility.

libs/viewer/src/lib/excel-document/excel-document.component.html, libs/viewer/src/lib/run-presentation/run-presentation.component.ts, libs/viewer/src/lib/viewer-app.component.ts
=> Possible fixes for calculating slides zoom and top-margin in Opera and Safari respectively.

libs/viewer/src/lib/viewer-app.component.less, libs/viewer/src/lib/viewer-app.component.ts
**What were done:**
1. Fixed multiple slides switching through bunch of consequenti ve mouse wheel events.
2. Presentations now get `FitToWidth` scale on opening by default.
3. Was returned possibility to scroll to top/bottom the slide before slide switching.
<details>
<legend>Take a look:</legend>
</details>
=> [WIP] Fixed slides switching by mouse wheel, slides fitted to width.

libs/viewer/src/lib/viewer-app.component.less
Fix for https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC/issues/61.
Related back-end changes: https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC/pull/77.
=> Discard pointer events only for slides.

libs/common-components/src/lib/page/page.component.ts, libs/viewer/src/lib/excel-page/excel-page.component.ts
This issue happens in image mode when the `this.data` is undefined the method `this.data.replace` fails.
```
DocumentComponent.html:7 ERROR TypeError: Cannot read property 'replace' of undefined
at PageComponent.ngOnChanges (groupdocs.examples.angular-common-components.js:1883)
at checkAndUpdateDirectiveInline (core.js:31906)
at checkAndUpdateNodeInline (core.js:44367)
at checkAndUpdateNode (core.js:44306)
at debugCheckAndUpdateNode (core.js:45328)
at debugCheckDirectivesFn (core.js:45271)
at Object.eval [as updateDirectives] (DocumentComponent.html:7)
at Object.debugUpdateDirectives [as updateDirectives] (core.js:45259)
at checkAndUpdateView (core.js:44271)
at callViewAction (core.js:44637)
```
=> Fixed issue 'Cannot read property 'replace' of undefined'

libs/annotation/src/lib/annotation/annotation.component.html, libs/annotation/src/lib/annotation/annotation.component.ts
**Problem:**
The text value of textarea-based annotations (textReplacement, textField, watermark) was not presented in their UI components.
**Solution:**
Were performed needed changes in annotation angular component.
=> Add visible text of textarea-based annotations and white background.

libs/annotation/src/lib/annotation-app.component.html, libs/annotation/src/lib/annotation-app.component.ts, libs/annotation/src/lib/annotation/annotation.component.html, libs/annotation/src/lib/annotation/annotation.component.ts
- Added button to toggle visibility of the annotations UI components for already added to documents annotations.
- If annotations were hidden they still exists in the front-end data model so will be added/edited on the document.
https://user-images.githubusercontent.com/17431807/115717556-f5368900-a382-11eb-9b62-7fa99d519b3b.gif
_Updated icon:_
=> Add button to toggle annotations visibility on UI.

libs/common-components/src/lib/page/page.component.ts, libs/viewer/src/lib/excel-page/excel-page.component.ts, libs/viewer/src/lib/thumbnails/thumbnails.component.ts, libs/viewer/src/lib/viewer-app.component.ts, libs/viewer/src/lib/viewer.module.ts
**Problem:**
We would like to support feature for using API URL different from default `localhost:8080` and we have step-by-step instruction here: https://products.conholdate.app/viewer/view/59mhVoboa6I5O4DL3/using-custom-host-url-step-by-step-guide.docx?preview=true.pdf.
But Viewer UI-package has an additional usage of the `localhost:8080` in it's module class declaration.
**Solution:**
- Usage of the `localhost:8080` was removed from the Viewer module class declaration.
- Additionally were removed usages of the `localhost:8080` from Viewer-app related common-components.
**Tests:**
- Running the Viewer-app (`.NET-WebForms`-backend) on localhost:8080 and on `random_ipv4:8080`.
- Opening files using general case with upload and using query-string parameter.
Related PR: …
=> [WIP] Remove localhost usages in Viewer module and related common-components.

libs/viewer/src/lib/viewer-app.component.ts
Explicitly open file form storage by setting 'file' query string parameter e.g 'file=sample.docx' or from URL by setting 'url' query parameter e.g. 'url=https%3A%2F%2Fwww.groupdocs.com%2F'
=> Different query string parameters for loading file from storage or URL

libs/viewer/src/lib/viewer-app.component.ts
This is the fix for one of the issues reported at https://forum.groupdocs.com/t/viewer-response-with-a-10x-bigger-file/10102. The code has been updated to use page data as a thumbnail instead of loading thumbnails from the server.
=> Skip loading thumbnails

libs/common-components/src/lib/config.service.ts
In case you specify query string parameter e.g. `?file=sample.docx` Viewer fails to open because of config service that is not stripping query but using `window.location.href`.
=> Viewer not working when a query string parameter is specified

libs/viewer/src/lib/thumbnails/thumbnails.component.html, libs/viewer/src/lib/thumbnails/thumbnails.component.ts, libs/viewer/src/lib/viewer-app.component.ts
In case when a thumbnail is missing e.g. page is not loaded we'll show an empty thumbnail with the page number.
=> Fix thumbnails rendering in image mode

libs/viewer/src/lib/viewer-app.component.ts
Fixed issue that lead to the following error in console
```
ERROR TypeError: Cannot read properties of null (reading 'pages')
```
=> Fixed viewer component pages preload when selecting new file

libs/common-components/src/lib/browse-files-modal/browse-files-modal.component.ts
This change fixes the issue when you can't navigate up to the previous folder when in case there are more than two folders. For example, if you navigate to `\folder-a\folder-b\`  you can't navigate back to the root folder.
=> Fixed up navigation in the file browser component.

libs/viewer/src/lib/excel-page/excel-page.component.less
This change fixes the issue caused by the global styles that are applied to all spreadsheets that are rendered to HTML. The global styles have been removed.
=> Fixed overlapping issues when viewing Excel spreadsheets in HTML mode

libs/viewer/src/lib/viewer-app.component.ts
Now backend search term is taken even if get query params are provided but search term from params is not pointed directly
=> Change logic of search term from backend
