groupdocs-total/GroupDocs.Total-Angular

.travis.yml, apps/editor/src/app/editor-app.component.ts, apps/editor/src/app/editor.service.ts, libs/common-components/src/lib/button/button.component.ts, libs/common-components/src/lib/editor.directive.ts, libs/common-components/src/lib/formatting.directive.ts, libs/common-components/src/lib/formatting.service.ts, libs/common-components/src/lib/page/page.component.ts, libs/common-components/src/lib/selection.service.ts, libs/common-components/src/lib/tabs/tabs.component.ts, libs/common-components/src/lib/top-toolbar/top-toolbar.component.ts, package.json
**Problem:**
There are several code problems in `editor-development` branch found by `tslint`.
**Solution:**
Code was fixed according to the `tslint` rules.
**Tests:**
Were started and manually checked available buttons on the toolbars in Editor and Viewer.
=> Fixes after ng lint.

apps/editor/src/app/editor-app.component.html, apps/editor/src/app/editor-app.component.ts, apps/editor/src/app/editor-export/editor-export.module.ts, apps/editor/src/app/editor.module.ts, libs/common-components/src/index.ts, libs/common-components/src/lib/common-components.module.ts, libs/common-components/src/lib/loading-mask-interceptor.service.ts, libs/common-components/src/lib/loading-mask.service.ts, libs/common-components/src/lib/loading-mask/loading-mask.component.html, libs/common-components/src/lib/loading-mask/loading-mask.component.less, libs/common-components/src/lib/loading-mask/loading-mask.component.ts
**Problem:**
We need full page preloader on any async action.
**Solution:**
Were added new service, component and interceptor for showing loading mask on each request.
=> Loading-mask component.

libs/common-components/src/lib/config.service.ts
=> Changing the config service class to get desired behavior.

libs/editor/src/lib/editor-app.component.ts
The same change as in https://github.com/groupdocs-total/GroupDocs.Total-Angular/pull/128 but for editor app.
=> Added usage of the defaultDocuement setting from editor configuration.

libs/editor/src/lib/editor-app.component.html, libs/editor/src/lib/editor-app.component.less
=> Update mobile styles for Editor app.

libs/editor/src/lib/editor-app.component.less
=> Fix for the expected scrolling document watermarks.

dist/libs/annotation/package.json, libs/annotation/package.json, libs/comparison/package.json, libs/conversion/package.json, libs/editor/package.json, libs/metadata/package.json, libs/signature/package.json, libs/viewer/package.json
The same changes and the same purpose as in https://github.com/groupdocs-total/GroupDocs.Total-Angular/pull/164.
=> Update common-components version for all apps.

apps/total-angular/src/app/app.module.ts, libs/viewer/src/lib/viewer-app.component.ts
**Related PR:**
https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-MVC/pull/66
_View file by passed absolute path in url-string parameter._
_View file by passed URL in url-string parameter._
=> [WIP] Opening files in Viewer using URL-string parameter.

apps/total-angular/src/app/app.module.ts, dist/libs/viewer/lib/viewer.module.d.ts, libs/viewer/src/lib/viewer-app.component.ts, libs/viewer/src/lib/viewer.module.ts
**Problem:**
Problem with app loading was met after upgrading the viewer npm package version to 0.8.11, it is presented on the screenshot above.
**Solution:**
Was applied the same approach as in the Viewer module in the conholdate.app including changing config service endpoint function.
_The initial issue:_
_How it works with the fix on 8080:_
=> Fix for issue with missed provider for ActivatedRoute in Viewer app.

libs/editor/src/lib/editor-app.component.html
=> [WIP] Hide/show Editor toolbar buttons in mobile/desktop modes.

libs/viewer/src/lib/run-presentation/run-presentation.component.html, libs/viewer/src/lib/thumbnails/thumbnails.component.ts, libs/viewer/src/lib/viewer-app.component.html, libs/viewer/src/lib/viewer-app.component.less, libs/viewer/src/lib/viewer-app.component.ts
**Were fixed:**
1. Added usage of the initial scaling during opening image files.
2. Updated scale value for the presentation mode.
3. Removed tooltips for next/prev buttons of presentation mode.
4. Added rounded background for next/prev buttons of presentation mode.
5. Added handling 16:10 aspect ratio in presentation mode (1280x800) traditional for retina displays.
And related code refactoring.
=> Improvements for presentation mode and images initial scale.

libs/viewer/src/lib/run-presentation/run-presentation.component.ts, libs/viewer/src/lib/viewer-app.component.html, libs/viewer/src/lib/viewer-app.component.ts
**What were improved:**
1. Corrected scaling related to aspect ratio.
2. Added check for fully loaded slide page before sliding to selected one.
3. Custom tooltips were replaced by native OS titles.
4. Added programmatically calculated top margin for the slide.
<details>
</details>
=> Fixes and improvements for presentations.

libs/metadata/ng-package.json, libs/metadata/package.json
Add the ng2-date-picker dependency to the metadata lib package.json
=> Add a dependency to the Metadata package.json

libs/viewer/src/lib/viewer-app.component.ts
Details about the error:
- https://blog.angular-university.io/angular-debugging/
- https://hackernoon.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4
- https://stackoverflow.com/questions/34364880/expression-has-changed-after-it-was-checked
Solution - manually trigger change detection by calling this.cdr.detectChanges();
=> Fixed issue 'Expression has changed after it was checked' in viewer-app.component by manually triggering change detection

libs/annotation/src/lib/annotation-app.component.html, libs/annotation/src/lib/annotation-app.component.ts, libs/common-components/src/lib/top-tab/top-tab.component.ts, package-lock.json
Reworked all annotation buttons to toggles. If to enable any annotation user can draw annotations as many as he need.
=> [GroupDocs.Annotation] button behaviour changed to toggle

libs/viewer/src/lib/viewer-app.component.ts
This is the fix for one of the issues reported at https://forum.groupdocs.com/t/viewer-response-with-a-10x-bigger-file/10102. A field `pagesToPreload` has been added to keep track of pages that have been requested to preload.
=> Make sure that a page is preloaded only once

libs/common-components/src/lib/render-print.directive.ts, libs/viewer/src/lib/viewer-app.component.ts
Viewer has been updated to print PDF in the nice print dialog instead of printing HTML or PNG.
These changes fixing https://github.com/groupdocs-total/GroupDocs.Total-for-Java/issues/3.
=> Print PDF instead of HTML or PNG pages

libs/annotation/src/lib/annotation-app.component.ts
Added functionality according to ANNOTATIONNET-2042
=> Implemented query string parameter to upload file

libs/common-components/src/lib/searchable.directive.ts, tsconfig.json
- class SearchableDirective (searchable.directive.ts)
- the main problem of delays and hang is cleanHighlight function
- pipe delays added to prevent input control send all text changes immediately if input is fast
- check of current searching process is running added
- check if input text is changed after current searching process is done added
Current problem
in some special cases of cleaning large amount of previously highlighted search results - input control
hangs for a while and doesn't show current user input changes. after all done - all works fine back
=> Large pptx presentation makes page hang

.github/workflows/build.yml, libs/common-components/src/index.ts, libs/common-components/src/lib/common-components.module.ts, libs/common-components/src/lib/modal/modal.component.less, libs/common-components/src/lib/scrollable-edited.directive.ts, libs/common-components/src/lib/viewport.service.ts, libs/viewer/src/lib/viewer-app.component.html, libs/viewer/src/lib/viewer.module.ts
This PR fixes the issues wit scroll described in #289.
=> Fix for #289
